# Generated by Django 3.2.23 on 2023-12-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0145_auto_20231220_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='test_cases',
            field=models.BooleanField(blank=True, null=True, verbose_name='load test cases'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.BooleanField(default=False, help_text='If true, the inputs and otuputs of every test case will be automatically added after the body.', verbose_name='include test cases'),
        ),
    ]
