# Generated by Django 3.2.23 on 2023-12-22 08:32

from django.db import migrations, models
import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0146_auto_20231221_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='test_cases',
            new_name='test_cases_enabled',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases_content',
            field=models.TextField(blank=True, validators=[judge.models.problem.disallowed_characters_validator], verbose_name='test cases content'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='test_cases',
            field=models.BooleanField(blank=True, null=True, verbose_name='override test cases from zip file'),
        ),
    ]
