# Generated by Django 3.2.23 on 2023-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0147_auto_20231222_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='test_cases_enabled',
            new_name='include_test_cases',
        ),
        migrations.RenameField(
            model_name='problemdata',
            old_name='test_cases',
            new_name='test_cases_override',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_cases_content',
        ),
        migrations.AddField(
            model_name='problemdata',
            name='test_cases_content',
            field=models.TextField(blank=True, verbose_name='test cases content'),
        ),
    ]
